output_dir                  = "builds"
headless                    = true
iso_dir                     = "iso"
iso_file                    = "OracleLinux-R8-U10-x86_64-dvd.iso"
iso_checksum                = "sha256:7676a80eeaafa16903eebb2abba147a3afe230b130cc066d56fdd6854d8da900"
os_name                     = "OracleLinux"
os_version                  = "8.10"
http_directory              = "http"
boot_wait                   = "10s"
shutdown_command            = "echo 'vagrant' | sudo -S /sbin/halt -h -p"
communicator                = "ssh"
ssh_port                    = 22
ssh_username                = "vagrant"
ssh_password                = "vagrant"
ssh_timeout                 = "10000s"
accelerator                 = "kvm"
vm_name                     = "oracle8-cis"
vm_machine_type             = "q35"
vm_cpu                      = 4
vm_memory                   = 4096
vm_disk                     = 56000
format                      = "qcow2"
efi_firmware                = "/usr/share/edk2/ovmf/OVMF_CODE.fd"
net_device                  = "virtio-net"
disk_interface              = "virtio"
disk_compression            = true
qemuargs                    = [["-cpu", "host"], ["-smp", "4"], ["-m", "4096"]]

