output_dir                  = "builds"
headless                    = true
iso_dir                     = "iso"
iso_file                    = "rhel-9.4-x86_64-dvd.iso"
iso_checksum                = "sha256:398561d7b66f1a4bf23664f4aa8f2cfbb3641aa2f01a320068e86bd1fc0e9076"
os_name                     = "RHEL"
os_version                  = "9.4"
http_directory              = "http"
boot_wait                   = "10s"
shutdown_command            = "echo 'vagrant' | sudo -S /sbin/halt -h -p"
communicator                = "ssh"
ssh_port                    = 22
ssh_username                = "vagrant"
ssh_password                = "vagrant"
ssh_timeout                 = "10000s"
accelerator                 = "kvm"
vm_name                     = "rhel9-cis"
vm_machine_type             = "q35"
vm_cpu                      = 4
vm_memory                   = 4096
vm_disk                     = 56000
format                      = "qcow2"
efi_firmware                = "/usr/share/edk2/ovmf/OVMF_CODE.fd"
net_device                  = "virtio-net"
disk_interface              = "virtio"
disk_compression            = true
qemuargs                    = [["-cpu", "host"], ["-smp", "4"], ["-m", "4096"]]
